site_name: 大学物理の問題集
theme:
  name: material
  features:
    - content.code.copy # コードをコピーするボタンを付ける（おまけ）
    - navigation.expand # ★これを追加！初期状態でサイドバーの各章を折りたたみます

markdown_extensions:
  - meta              # ★これがないとFrontmatter（メタデータ）を認識しません
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search
  - awesome-pages
  - tags              # ★これを入れると、サイト上に綺麗なタグが自動表示されます


# mkdocs.yml の一番下に追加
nav:
  - 力学:
    - 第1章:
      - mechanics/01/01_010.md
      - mechanics/01/01_020.md
