site_name: 大学物理の問題集
theme:
  name: material
  custom_dir: overrides
  font:
    text: Noto Sans JP  # 👈 サイト全体の文字を Noto Sans JP に！
    code: Roboto Mono   # 👈 数式やコード用のフォント（そのままでOK）
  features:
    - content.code.copy 
    - navigation.footer # コードをコピーするボタンを付ける（おまけ）
    # - navigation.expand # ★これを追加！初期状態でサイドバーの各章を折りたたみます
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: ダークモードに切り替え

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: ライトモードに切り替え

extra:
  analytics:
    provider: google
    property: G-FDK0HJQRC9

markdown_extensions:
  - meta
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: math
          class: arithmatex
          format: !!python/name:pymdownx.arithmatex.fence_mathjax_format
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg


extra_javascript:
  - javascripts/mathjax.js
  - javascripts/problem-filter.js
  - javascripts/share.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

hooks:
  - hooks/problem_index.py

not_in_nav: |
  tag-index.md

plugins:
  - search
  - awesome-pages
  - tags:
      tags_file: tag-index.md
                  


extra_css:
  - stylesheets/extra.css
