"""Split MkDocs' sitemap into subject-specific sitemap files."""

from copy import deepcopy
from datetime import date
from pathlib import Path
from typing import Optional
from urllib.parse import urlparse
import xml.etree.ElementTree as ET


SITEMAP_NS = "http://www.sitemaps.org/schemas/sitemap/0.9"

SUBJECT_SITEMAPS = {
    "01mechanics": "sitemap-mechanics.xml",
    "02electromagnetism": "sitemap-electromagnetism.xml",
    "03thermodynamics": "sitemap-thermodynamics.xml",
    "04quantum_mechanics": "sitemap-quantum-mechanics.xml",
    "05statistical_mechanics": "sitemap-statistical-mechanics.xml",
}


def _subject_slug(url: str, site_path: str) -> Optional[str]:
    path = urlparse(url).path
    if site_path != "/" and path.startswith(site_path):
        path = path[len(site_path) :]
    first_segment = path.strip("/").split("/", 1)[0]
    return first_segment if first_segment in SUBJECT_SITEMAPS else None


def _write_urlset(path: Path, entries: list[ET.Element]) -> None:
    root = ET.Element(f"{{{SITEMAP_NS}}}urlset")
    for entry in entries:
        root.append(deepcopy(entry))
    ET.ElementTree(root).write(path, encoding="utf-8", xml_declaration=True)


def _latest_lastmod(entries: list[ET.Element]) -> str:
    values = [
        element.text
        for entry in entries
        if (element := entry.find(f"{{{SITEMAP_NS}}}lastmod")) is not None
        and element.text
    ]
    return max(values, default=date.today().isoformat())


def on_post_build(config, **kwargs):
    site_dir = Path(config["site_dir"])
    source = site_dir / "sitemap.xml"
    if not source.exists():
        raise RuntimeError("sitemap.xml was not generated by MkDocs")

    ET.register_namespace("", SITEMAP_NS)
    entries = list(ET.parse(source).getroot())
    site_url = config["site_url"].rstrip("/") + "/"
    site_path = urlparse(site_url).path

    grouped = {slug: [] for slug in SUBJECT_SITEMAPS}
    main_entries = []

    for entry in entries:
        loc = entry.find(f"{{{SITEMAP_NS}}}loc")
        slug = _subject_slug(loc.text, site_path) if loc is not None and loc.text else None
        if slug:
            grouped[slug].append(entry)
        else:
            main_entries.append(entry)

    generated = [("sitemap-main.xml", main_entries)]
    generated.extend(
        (filename, grouped[slug])
        for slug, filename in SUBJECT_SITEMAPS.items()
    )

    for filename, group_entries in generated:
        _write_urlset(site_dir / filename, group_entries)

    index = ET.Element(f"{{{SITEMAP_NS}}}sitemapindex")
    for filename, group_entries in generated:
        sitemap = ET.SubElement(index, f"{{{SITEMAP_NS}}}sitemap")
        ET.SubElement(sitemap, f"{{{SITEMAP_NS}}}loc").text = site_url + filename
        ET.SubElement(sitemap, f"{{{SITEMAP_NS}}}lastmod").text = _latest_lastmod(
            group_entries
        )

    ET.ElementTree(index).write(
        site_dir / "sitemap-index.xml",
        encoding="utf-8",
        xml_declaration=True,
    )
